### ISSUE TITLE
"pip install pandora" not working anymore ?

### ISSUE THREAD

**Issue by SylvainJay** [CNES/Pandora#6]
Hello,

It seems that "pip install pandora" command does not work anymore (see below). I have used this package for nearly one year, and this is the first time I can't install properly in a new environment. Any idea where this comes from ?

Thank you very much !

Sylvain

Collecting pandora
  Downloading pandora-1.2.2.tar.gz (37.1 MB)
     ---------------------------------------- 37.1/37.1 MB 8.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting transitions
  Downloading transitions-0.8.11-py2.py3-none-any.whl (83 kB)
     ---------------------------------------- 83.9/83.9 KB ? eta 0:00:00
Collecting xarray>=0.13.*
  Downloading xarray-2022.3.0-py3-none-any.whl (870 kB)
     ---------------------------------------- 870.9/870.9 KB 9.3 MB/s eta 0:00:00
Collecting rasterio
  Downloading rasterio-1.2.10.tar.gz (2.3 MB)
     ---------------------------------------- 2.3/2.3 MB 7.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
      ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by njimenezd** [comment]
Hello, 

It seems like you have a local problem with GDAL which is not directly related to Pandora, probably due to an update of the latest Rasterio version. Without further information of your local environment we have no means to reproduce the error. 

However, from your error log it looks like you are installing Pandora in Windows, is that correct? In that case, we found this error has been solved and described here https://opensourceoptions.com/blog/install-rasterio-for-windows-with-pip-or-conda/, you may try and tell us if it worked. 

Thanks for using Pandora.

**Comment by SylvainJay** [comment]
Thank you for your quick answer !

Actually, I had problems when installing pandora and pandora[sgm] with miniconda3 on a new machine on Windows. The above problem (which, in my case, can effectively be solved by installing rasterio with conda before running pip install pandora) was only part of all the problems I had ! The other ones being to install a proper version of build tools for visual studio, as well as to install MingW (https://sourceforge.net/projects/mingw/) + mingw32-gcc-g++ before adding C:\MinGW\bin to system path (if anyone interested...). 

Thanks again anyway !
